require('user.settings')
require('user.keymaps')
require('user.colorscheme')
require('user.lsp.cmp')
-- require('user.lsp.lsp_setup')
require('user.plugins')
require('user.treesitter')
-- require('user.lualine')
require('user.lualine0')
require('user.bufferline')
require('user.nvimtree')
require('user.telescope')
require('user.alpha')
require('user.autopairs')
-- require('user.org-mode')
require('user.whichkey')
require('user.minimap')
require('user.zen')
require('user.gitsigns')
require('user.neoscroll')
require('user.comment')
require('user.toggleterm')
